version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.8.0
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock"  }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix test
      - run: mix format --check-formatted
      - run: mix credo
      - run: mix dialyzer --halt-exit-status
      - store_test_results:
          path: _build/test/lib/elixir-ocr

